=== blagojevic-uros/XML/Spring-JAX-RS/src/main/resources/podaci/schemas/interesovanje.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
           vc:minVersion="1.1" xmlns:it="http://ftn.uns.ac.rs/vakcina/interesovanje"
           xmlns:tp="http://ftn.uns.ac.rs/vakcine/tipovi" xmlns:fv="http://ftn.uns.ac.rs/vakcina/tipovi"
           targetNamespace="http://ftn.uns.ac.rs/vakcina/interesovanje">
    <xs:import namespace="http://ftn.uns.ac.rs/vakcina/tipovi" schemaLocation="types.xsd"/>
    <xs:element name="interesovanje">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="licni_podaci">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="drzavljanstvo">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="property"/>
                                            <xs:attribute name="datatype"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="JMBG">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="fv:JMBG">
                                            <xs:attribute name="property"/>
                                            <xs:attribute name="datatype"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="ime" type="xs:string"/>
                            <xs:element name="prezime" type="xs:string"/>
                            <xs:element name="email" type="fv:email"> </xs:element>
                            <xs:element name="mobilni_telefon" type="fv:mobilni_telefon"> </xs:element>
                            <xs:element name="fiksni_telefon" type="fv:fiksni_telefon">
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="lokacija_vakcinisanja">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="prop"/>
                                <xs:attribute name="datatype"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="tip_vakcine">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="fv:tip_vakcine">
                                <xs:attribute name="property"/>
                                <xs:attribute name="datatype"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="datum">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:date">
                                <xs:attribute name="property"/>
                                <xs:attribute name="datatype"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="potpis" type="xs:string"/>
                <xs:element minOccurs="0" name="davalac_krvi"/>
            </xs:sequence>
            <xs:attribute name="potvrda_o_vakcinisanju" type="xs:anyURI"/>
            <xs:attribute name="saglasnost_za_imunizaciju" type="xs:anyURI"/>
            <xs:attribute name="id" type="xs:string"/>
            <xs:attribute name="about" type="xs:anyURI"/>
            <xs:attribute name="rel" type="xs:string"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== blagojevic-uros/XML/xml/interesovanje.xml
<?xml version="1.0" encoding="UTF-8"?>
<interesovanje xmlns="http://ftn.uns.ac.rs/vakcina/interesovanje"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:pred="http://www.ftn.uns.ac.rs/rdf/interesovanje/predicate/"
    xsi:schemaLocation="../schemas/interesovanje.xsd"
    saglasnost_za_imunizaciju="http://www.ftn-vakcine.rs/saglanost/123123"
    id="1">
    <licni_podaci>
        <drzavljanstvo>Drzavljanin_RS</drzavljanstvo>
        <JMBG property="pred:JMBG">094388852429</JMBG>
        <ime>Zoran</ime>
        <prezime>Petrović</prezime>
        <email>petko@gmail.com</email>
        <mobilni_telefon>0684281384</mobilni_telefon>
        <fiksni_telefon>017489976</fiksni_telefon>
    </licni_podaci>
    <lokacija_vakcinisanja>Vranje</lokacija_vakcinisanja>
    <tip_vakcine>Pfizer-BioNTech</tip_vakcine>
    <datum>2021-05-07</datum>
    <potpis>ZPetrović</potpis>
    <davalac_krvi></davalac_krvi>
</interesovanje>

=== blagojevic-uros/XML/Spring-JAX-RS/src/main/resources/podaci/xml/interesovanje.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../xsl/grddl.xsl"?>
<interesovanje xmlns="http://ftn.uns.ac.rs/vakcina/interesovanje"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:pred="http://www.ftn.uns.ac.rs/rdf/interesovanje/predicate/"
    xsi:schemaLocation="../schemas/interesovanje.xsd"
    about="http://www.ftn.uns.ac.rs/rdf/interesovanje/123"
               rel="pred:saglasnostOd"
    id="123" href="http://www.ftn.uns.ac.rs/rdf/saglasnost/123">
    <licni_podaci>
        <drzavljanstvo property="pred:drzavljanstvo">Drzavljanin_RS</drzavljanstvo>
        <JMBG property="pred:jmbg">094388852429</JMBG>
        <ime>Zoran</ime>
        <prezime>Petrović</prezime>
        <email>petko@gmail.com</email>
        <mobilni_telefon>0684281384</mobilni_telefon>
        <fiksni_telefon>017489976</fiksni_telefon>
    </licni_podaci>
    <lokacija_vakcinisanja>Vranje</lokacija_vakcinisanja>
    <tip_vakcine property="pred:vakcina">Pfizer-BioNTech</tip_vakcine>
    <datum>2021-05-07</datum>
    <potpis>ZPetrović</potpis>
    <davalac_krvi></davalac_krvi>
</interesovanje>
