=== blagojevic-uros/XML/Spring-JAX-RS/src/main/resources/podaci/schemas/potvrda_o_vakcinisanju.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.1" targetNamespace="http://ftn.uns.ac.rs/vakcina/potvrda"
    xmlns:pov="http://ftn.uns.ac.rs/vakcina/potvrda" xmlns:fv="http://ftn.uns.ac.rs/vakcina/tipovi">
    <xs:import namespace="http://ftn.uns.ac.rs/vakcina/tipovi" schemaLocation="types.xsd"/>
    <xs:element name="potvrda_o_vakcinaciji">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="sifra_potvrde" type="fv:sifra"/>
                <xs:element name="licni_podaci" type="pov:Licni_podaci"/>
                <xs:element name="informacije_vakcinacije" type="pov:informacije_vakcinacija"/>
                <xs:element name="datum_izdavanja_potvrde">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:date">
                                <xs:attribute name="property"/>
                                <xs:attribute name="datatype"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="zdravstvena_ustanova" type="xs:string"/>
                <xs:element name="qr_kod" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="interesovanje" type="xs:anyURI"/>
            <xs:attribute name="potvrda_o_vakcinisanju" type="xs:anyURI"/>
            <xs:attribute name="saglasnost_za_imunizaciju" type="xs:anyURI"/>
            <xs:attribute name="id" type="xs:string"/>
            <xs:attribute name="about" type="xs:anyURI"/>
            <xs:attribute name="rel" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="Licni_podaci">
        <xs:sequence>
            <xs:element name="ime_prezime" type="fv:Ime_prezime"> </xs:element>
            <xs:element name="pol" maxOccurs="1" minOccurs="1" type="fv:pol"> </xs:element>
            <xs:element name="JMBG">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="fv:JMBG">
                            <xs:attribute name="property"/>
                            <xs:attribute name="datatype"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="datum_rodjenja" type="xs:date"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="informacije_vakcinacija">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="1" ref="pov:informacije_o_dozi"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="informacije_o_dozi" type="pov:TInfomacije_o_dozi"> </xs:element>
    <xs:complexType name="TInfomacije_o_dozi">
        <xs:sequence>
            <xs:element name="naziv_vakcine">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="fv:tip_vakcine">
                            <xs:attribute name="property"/>
                            <xs:attribute name="datatype"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="datum_doze" type="xs:date"/>
            <xs:element name="broj_serije" type="xs:positiveInteger"/>
            <xs:element name="broj_doze" type="xs:positiveInteger"/>
            <xs:element name="zdravstena_ustanova">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="property"/>
                            <xs:attribute name="datatype"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== blagojevic-uros/XML/Spring-JAX-RS/src/main/resources/podaci/xml/potvrda_o_vakcinisanju.xml
<?xml version="1.0" encoding="UTF-8"?>
<potvrda_o_vakcinaciji xmlns="http://ftn.uns.ac.rs/vakcina/potvrda"
                       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                       about="http://www.ftn.uns.ac.rs/rdf/potvrda/123"
                       xmlns:pred="http://www.ftn.uns.ac.rs/rdf/potvrda/predicate/"
                       xsi:schemaLocation="http://ftn.uns.ac.rs/vakcina/potvrda ../schemas/potvrda_o_vakcinisanju.xsd">
    <sifra_potvrde>1232131313/12</sifra_potvrde>
    <licni_podaci>
        <ime_prezime>
            <ime xmlns="http://ftn.uns.ac.rs/vakcina/tipovi">Pera</ime>
            <prezime xmlns="http://ftn.uns.ac.rs/vakcina/tipovi">Peric</prezime>
        </ime_prezime>
        <pol>M</pol>
        <JMBG property="pred:jmbg">1231231231234</JMBG>
        <datum_rodjenja>1999-08-08</datum_rodjenja>
    </licni_podaci>
    <informacije_vakcinacije>
        <informacije_o_dozi>
            <naziv_vakcine property="pred:vakcina">Moderna</naziv_vakcine>
            <datum_doze>2021-12-12</datum_doze>
            <broj_serije>123</broj_serije>
            <broj_doze>1</broj_doze>
            <zdravstena_ustanova property="pred:lokacijaVakcinisanja">Novi Sad Promenada</zdravstena_ustanova>
        </informacije_o_dozi>
    </informacije_vakcinacije>
    <datum_izdavanja_potvrde property="pred:datum">2021-12-12</datum_izdavanja_potvrde>
    <zdravstvena_ustanova>Novi Sad Bolnica</zdravstvena_ustanova>
    <qr_kod></qr_kod>
</potvrda_o_vakcinaciji>

=== blagojevic-uros/XML/xml/potvrda_o_vakcinisanju.xml
<?xml version="1.0" encoding="UTF-8"?>
<potvrda_o_vakcinaciji xmlns="http://www.ftn.uns.ac.rs/vakcine/potvrda"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/vakcine/potvrda file:/F:/4.%20Godina/XML/XML/schemas/potvrda_o_vakcinisanju.xsd">
    <sifra_potvrde>4778790-2559987</sifra_potvrde>
    <licni_podaci>
        <ime_prezime>
            <ime>Darko</ime>
            <prezime>Tica</prezime>
        </ime_prezime>
        <pol>Musko</pol>
        <JMBG>042999985249</JMBG>
        <datum_rodjenja>1999-04-05</datum_rodjenja>
    </licni_podaci>
    <informacije_vakcinacije>
        <informacije_o_dozi>
            <naziv_vakcine>Pfizer</naziv_vakcine>
            <datum_doze>2021-04-05</datum_doze>
            <broj_serije>3245</broj_serije>
            <broj_doze>1</broj_doze>
            <zdravstena_ustanova>Opšta bolnica Bečej</zdravstena_ustanova>
        </informacije_o_dozi>
        <informacije_o_dozi>
            <naziv_vakcine>Pfizer</naziv_vakcine>
            <datum_doze>2021-04-19</datum_doze>
            <broj_serije>3455</broj_serije>
            <broj_doze>2</broj_doze>
            <zdravstena_ustanova>Opšta bolnica Promenada</zdravstena_ustanova>
        </informacije_o_dozi>
    </informacije_vakcinacije>
    <datum_izdavanja_potvrde>2021-02-07</datum_izdavanja_potvrde>
    <zdravstvena_ustanova>Opšta bolnica Bečej</zdravstvena_ustanova>
    <qr_kod></qr_kod>
    
</potvrda_o_vakcinaciji>
