=== blagojevic-uros/XML/Spring-JAX-RS/src/main/resources/podaci/schemas/saglanost_za_imunizaciju.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.1" targetNamespace="http://ftn.uns.ac.rs/vakcina/saglasnost"
    xmlns:fk="http://ftn.uns.ac.rs/vakcina/saglasnost"
    xmlns:fv="http://ftn.uns.ac.rs/vakcina/tipovi">
    <xs:import namespace="http://ftn.uns.ac.rs/vakcina/tipovi" schemaLocation="types.xsd"/>
    <xs:element name="saglasnost_za_imunizaciju">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="fk:licni_podaci"/>
                <xs:element name="saglasnost">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element minOccurs="0" name="saglasan_sam"/>
                            <xs:element name="naziv_leka" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="potpis" type="xs:string"/>
                <xs:element name="datum">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:date">
                                <xs:attribute name="property"/>
                                <xs:attribute name="datatype"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element ref="fk:evidencija_o_vakcinaciji" minOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="potvrda_o_vakcinisanju"/>
            <xs:attribute name="interesovanje"/>
            <xs:attribute name="id"/>
            <xs:attribute name="about"/>
            <xs:attribute name="rel"/>
            <xs:attribute name="href"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="evidencija_o_vakcinaciji">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="zdravstvena_ustanova" type="xs:string"/>
                <xs:element name="vakcinijski_punkt" type="xs:string"/>
                <xs:element ref="fk:lekar"/>
                <xs:element name="tabela_vakcinisanja">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" ref="fk:vakcinisanje" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TLekar">
        <xs:sequence>
            <xs:element name="ime" type="xs:string"/>
            <xs:element name="prezime" type="xs:string"/>
            <xs:element name="faksimil" type="xs:string"/>
            <xs:element name="broj_telefona">
                <xs:simpleType>
                    <xs:restriction base="fv:mobilni_telefon"> </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TVakcinisanje">
        <xs:sequence>
            <xs:element name="naziv_vakcine">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="fv:tip_vakcine">
                            <xs:attribute name="property"/>
                            <xs:attribute name="datatype"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="datum_davanja" type="xs:date"/>
            <xs:element name="nacin_davanja" type="xs:string"/>
            <xs:element name="ekstremitet">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="leva_ruka"/>
                        <xs:enumeration value="desna_ruka"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="serija_vakcine" type="xs:string"/>
            <xs:element name="proizvodjac" type="fv:tip_vakcine"/>
            <xs:element name="nezeljena_reakcija" type="xs:string"/>
            <xs:element name="potpis_lekara" type="xs:string"/>
            <xs:element name="privremene_kontraindikacije">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="datum" type="xs:date"/>
                        <xs:element name="dijagnoza" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element minOccurs="0" name="odluka_komisije" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="licni_podaci">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="fk:drzavljanstvo"/>
                <xs:element name="prezime" type="xs:string"/>
                <xs:element name="ime" type="xs:string"/>
                <xs:element name="ime_roditelja" type="xs:string"/>
                <xs:element name="pol">
                    <xs:simpleType>
                        <xs:restriction base="fv:pol"> </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="datum_rodjenja" type="xs:date"/>
                <xs:element name="mesto_rodjenja" type="xs:string"/>
                <xs:element name="adresa">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ulica_broj" type="xs:string"/>
                            <xs:element name="mesto_naselje" type="xs:string"/>
                            <xs:element name="opstina_grad" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="fiksni_broj" type="fv:fiksni_telefon"/>
                <xs:element name="mobilni_broj" type="fv:mobilni_telefon"/>
                <xs:element name="email" type="fv:email"/>
                <xs:element ref="fk:radni_status"/>
                <xs:element minOccurs="0" ref="fk:zanimanje_zaposlenog"/>
                <xs:element minOccurs="0" name="korisnik_soc_zastite">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="naziv_opstine" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="property"/>
                        <xs:attribute name="datatype"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="drzavljanstvo">
        <xs:complexType>
            <xs:choice>
                <xs:element ref="fk:srpsko"/>
                <xs:element ref="fk:strano"/>
            </xs:choice>
            <xs:attribute name="property"/>
            <xs:attribute name="datatype"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="srpsko">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="JMBG">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="fv:JMBG">
                                <xs:attribute name="property"/>
                                <xs:attribute name="datatype"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="strano">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="naziv_drzavljanstva" type="xs:string"/>
                <xs:element name="broj_pasosa_ebs">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="fv:broj_pasosa">
                                <xs:attribute name="property"/>
                                <xs:attribute name="datatype"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="radni_status">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="zaposlen"/>
                <xs:enumeration value="nezaposlen"/>
                <xs:enumeration value="penzioner"/>
                <xs:enumeration value="ucenik"/>
                <xs:enumeration value="student"/>
                <xs:enumeration value="dete"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="zanimanje_zaposlenog">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="zdravstvena_zastita"/>
                <xs:enumeration value="socijalna_zastita"/>
                <xs:enumeration value="prosveta"/>
                <xs:enumeration value="mup"/>
                <xs:enumeration value="vojska_rs"/>
                <xs:enumeration value="drugo"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="vakcinisanje" type="fk:TVakcinisanje"> </xs:element>
    <xs:element name="lekar" type="fk:TLekar"> </xs:element>
</xs:schema>

=== blagojevic-uros/XML/Spring-JAX-RS/src/main/resources/podaci/xml/saglasnost_za_imunizaciju.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../xsl/grddl.xsl"?>
<saglasnost_za_imunizaciju xmlns="http://ftn.uns.ac.rs/vakcina/saglasnost"
                           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                           xmlns:pred="http://www.ftn.uns.ac.rs/rdf/saglasnost/predicate/"
                           xsi:schemaLocation="../schemas/saglanost_za_imunizaciju.xsd"
                           about="http://www.ftn.uns.ac.rs/rdf/saglasnost/123"
                           id="123" rel="pred:potvrda"
                           href="http://www.ftn.uns.ac.rs/rdf/potvrda/123">
    <licni_podaci>
        <drzavljanstvo>
            <srpsko>
                <JMBG property="pred:jmbg">0808999742049</JMBG>
            </srpsko>
        </drzavljanstvo>
        <prezime>Petrovic</prezime>
        <ime>Pera</ime>
        <ime_roditelja>Pera</ime_roditelja>
        <pol>M</pol>
        <datum_rodjenja>1999-02-02</datum_rodjenja>
        <mesto_rodjenja>Novi sad</mesto_rodjenja>
        <adresa>
            <ulica_broj>43</ulica_broj>
            <mesto_naselje>Novi Sad</mesto_naselje>
            <opstina_grad>Novi Sad</opstina_grad>
        </adresa>
        <fiksni_broj>011134134</fiksni_broj>
        <mobilni_broj>069123123</mobilni_broj>
        <email>pera.petrovic@gmail.com</email>
        <radni_status>zaposlen</radni_status>
        <zanimanje_zaposlenog>prosveta</zanimanje_zaposlenog>
        <korisnik_soc_zastite>
            <naziv_opstine>Novi Sad</naziv_opstine>
        </korisnik_soc_zastite>
    </licni_podaci>
    <saglasnost>
        <naziv_leka>Brufen</naziv_leka>
    </saglasnost>
    <potpis>PPera</potpis>
    <datum property="pred:datum">2021-12-12</datum>
    <evidencija_o_vakcinaciji>
        <zdravstvena_ustanova>Bolnica Novi Sad</zdravstvena_ustanova>
        <vakcinijski_punkt>123</vakcinijski_punkt>
        <lekar>
            <ime>Mara</ime>
            <prezime>Maric</prezime>
            <faksimil>test</faksimil>
            <broj_telefona>06123123123</broj_telefona>
        </lekar>
        <tabela_vakcinisanja>
            <vakcinisanje>
                <naziv_vakcine property="pred:vakcina">Pfizer-BioNTech</naziv_vakcine>
                <datum_davanja>2021-12-12</datum_davanja>
                <nacin_davanja>test</nacin_davanja>
                <ekstremitet>leva_ruka</ekstremitet>
                <serija_vakcine>123123</serija_vakcine>
                <proizvodjac >Pfizer-BioNTech</proizvodjac>
                <nezeljena_reakcija>Nema</nezeljena_reakcija>
                <potpis_lekara>MMara</potpis_lekara>
                <privremene_kontraindikacije>
                    <datum>2021-12-12</datum>
                    <dijagnoza>Nema</dijagnoza>
                </privremene_kontraindikacije>
            </vakcinisanje>
        </tabela_vakcinisanja>
    </evidencija_o_vakcinaciji>
</saglasnost_za_imunizaciju>

=== blagojevic-uros/XML/xml/saglanost_za_imunizaciju.xml
<?xml version="1.0" encoding="UTF-8"?>
<saglasnost_za_imunizaciju xmlns="http://www.ftn-vakcine.rs/saglanost"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn-vakcine.rs/saglanost ../schemas/saglanost_za_imunizaciju.xsd"
    interesovanje="123123">
    <licni_podaci>
        <drzavljanstvo>
            <srpsko>
            <JMBG>1202999850111</JMBG>    
            </srpsko>
        </drzavljanstvo>
        <prezime>Petrovic</prezime>
        <ime>Pera</ime>
        <ime_roditelja>Pera</ime_roditelja>
        <pol>M</pol>
        <datum_rodjenja>1999-02-02</datum_rodjenja>
        <mesto_rodjenja>Novi sad</mesto_rodjenja>
        <adresa>
            <ulica_broj>43</ulica_broj>
            <mesto_naselje>Novi Sad</mesto_naselje>
            <opstina_grad>Novi Sad</opstina_grad>
        </adresa>
        <fiksni_broj>011134134</fiksni_broj>
        <mobilni_broj>069123123</mobilni_broj>
        <email>pera.petrovic@gmail.com</email>
        <radni_status>zaposlen</radni_status>
        <zanimanje_zaposlenog>prosveta</zanimanje_zaposlenog>
        <korisnik_soc_zastite>
            <naziv_opstine>Novi Sad</naziv_opstine>
        </korisnik_soc_zastite>
    </licni_podaci>
    <saglanost>
        <naziv_leka>Brufen</naziv_leka>
    </saglanost>
    <potpis>PPera</potpis>
    <datum>2021-12-12</datum>
    <evidencija_o_vakcinaciji>
        <zdravstvena_ustanova>Bolnica Novi Sad</zdravstvena_ustanova>
        <vakcinijski_punkt>123</vakcinijski_punkt>
        <lekar>
            <ime>Mara</ime>
            <prezime>Maric</prezime>
            <faksimil>test</faksimil>
            <broj_telefona>06123123123</broj_telefona>
        </lekar>
        <tabela_vakcinisanja>
            <vakcinisanje>
                <naziv_vakcine>Moderna</naziv_vakcine>
                <datum_davanja>2021-12-12</datum_davanja>
                <nacin_davanja>test</nacin_davanja>
                <ekstremitet>leva_ruka</ekstremitet>
                <serija_vakcine>123123</serija_vakcine>
                <proizvodjac>Moderna</proizvodjac>
                <nezeljena_reakcija>Nema</nezeljena_reakcija>
                <potpis_lekara>MMara</potpis_lekara>
                <privremene_kontraindikacije>
                    <datum>2021-12-12</datum>
                    <dijagnoza>Nema</dijagnoza>
                </privremene_kontraindikacije>
            </vakcinisanje>
        </tabela_vakcinisanja>
    </evidencija_o_vakcinaciji>
</saglasnost_za_imunizaciju>
