=== blagojevic-uros/XML/Spring-JAX-RS/src/main/resources/podaci/schemas/zahtev_za_sertifikat.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.1" targetNamespace="http://ftn.uns.ac.rs/vakcina/zahtev"
    xmlns:fv="http://ftn.uns.ac.rs/vakcina/tipovi" xmlns="http://ftn.uns.ac.rs/vakcina/zahtev">
    <xs:import namespace="http://ftn.uns.ac.rs/vakcina/tipovi" schemaLocation="types.xsd"/>
    <xs:element name="zahtev_za_sertifikat">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="licni_podaci">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ime_prezime" type="fv:Ime_prezime"> </xs:element>
                            <xs:element name="datum_rodjenja" type="xs:date"/>
                            <xs:element name="pol" type="fv:pol"/>
                            <xs:element name="JMBG">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="fv:JMBG">
                                            <xs:attribute name="prop"/>
                                            <xs:attribute name="datatype"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="broj_pasosa">
                                <xs:simpleType>
                                    <xs:restriction base="fv:broj_pasosa"> </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="razlog_za_zahtev" type="xs:string"/>
                <xs:element name="mesto">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="prop"/>
                                <xs:attribute name="datatype"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="datum_zahteva">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:date">
                                <xs:attribute name="prop"/>
                                <xs:attribute name="datatype"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="potpis" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="sertifikat"/>
            <xs:attribute name="id"/>
            <xs:attribute name="about"/>
            <xs:attribute name="rel"/>
            <xs:attribute name="href"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== blagojevic-uros/XML/sluzbenik/src/main/resources/podaci/xml/zahtev_za_sertifikat.xml
<?xml version="1.0" encoding="UTF-8"?>
<zahtev_za_sertifikat xmlns="http://ftn.uns.ac.rs/vakcina/zahtev"
                      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                      xmlns:pred="http://www.ftn.uns.ac.rs/rdf/zahtev/predicate/"
                      xsi:schemaLocation="../schemas/zahtev_za_sertifikat.xsd"
                      about="http://www.ftn.uns.ac.rs/rdf/zahtev/123"
                      rel="pred:zahtevOd" href="http://www.ftn.uns.ac.rs/rdf/potvrda/123">
    <licni_podaci>
        <ime_prezime>
            <ime xmlns="http://www.ftn-vakcine.rs/types">Aleksandar</ime>
            <prezime xmlns="http://www.ftn-vakcine.rs/types">Jovanovic</prezime>
        </ime_prezime>
        <datum_rodjenja>1999-08-08</datum_rodjenja>
        <pol>M</pol>
        <JMBG  property="pred:jmbg">0808999742049</JMBG>
        <broj_pasosa>052425937</broj_pasosa>
    </licni_podaci>
    <razlog_za_zahtev>Putovanje</razlog_za_zahtev>
    <mesto prop="pred:mesto">Novi Sad</mesto>
    <datum_zahteva prop="pred:datum">2021-12-03</datum_zahteva>
    <potpis>AJovanoviÄ‡</potpis>
</zahtev_za_sertifikat>

=== blagojevic-uros/XML/xml/zahtev_za_sertifikat.xml
<?xml version="1.0" encoding="UTF-8"?>
<zahtev_za_sertifikat xmlns="http://ftn.uns.ac.rs/vakcine/sertifikat"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://ftn.uns.ac.rs/vakcine/sertifikat file:/F:/4.%20Godina/XML/XML/schemas/zahtev_za_sertifikat.xsd">
    <licni_podaci>
        <ime_prezime>
            <ime>Aleksandar</ime>
            <prezime>Jovanović</prezime>
        </ime_prezime>
        <datum_rodjenja>1999-08-08</datum_rodjenja>
        <pol>Musko</pol>
        <JMBG>0808999742049</JMBG>
        <broj_pasosa>052425937</broj_pasosa>
    </licni_podaci>
    <razlog_za_zahtev>Putovanje</razlog_za_zahtev>
    <mesto>Novi Sad</mesto>
    <datum_zahteva>2021-12-03</datum_zahteva>
    <potpis>AJovanović</potpis>
</zahtev_za_sertifikat>

=== blagojevic-uros/XML/Spring-JAX-RS/src/main/resources/podaci/xml/zahtev_za_sertifikat.xml
<?xml version="1.0" encoding="UTF-8"?>
<zahtev_za_sertifikat xmlns="http://www.ftn-vakcine/zahtev_sertifikat"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn-vakcine/zahtev_sertifikat ../schemas/zahtev_za_sertifikat.xsd">
    <licni_podaci>
        <ime_prezime>
            <ime xmlns="http://www.ftn-vakcine.rs/types">Aleksandar</ime>
            <prezime xmlns="http://www.ftn-vakcine.rs/types">Jovanovic</prezime>
        </ime_prezime>
        <datum_rodjenja>1999-08-08</datum_rodjenja>
        <pol>M</pol>
        <JMBG>0808999742049</JMBG>
        <broj_pasosa>052425937</broj_pasosa>
    </licni_podaci>
    <razlog_za_zahtev>Putovanje</razlog_za_zahtev>
    <mesto>Novi Sad</mesto>
    <datum_zahteva>2021-12-03</datum_zahteva>
    <potpis>AJovanoviÄ‡</potpis>
</zahtev_za_sertifikat>
