=== blagojevic-uros/XML/Spring-JAX-RS/src/main/resources/podaci/schemas/zeleni_sertifikat.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.1" xmlns:fv="http://www.ftn-vakcine.rs/types"
    targetNamespace="http://www.ftn-vakcine.rs/sertifikat"
    xmlns:st="http://www.ftn-vakcine.rs/sertifikat">
    <xs:import namespace="http://www.ftn-vakcine.rs/types" schemaLocation="types.xsd"/>
    <xs:element name="zeleni_sertifikat">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="QR_code" type="xs:string"/>
                <xs:element name="broj_sertifikata" type="fv:sifra"> </xs:element>
                <xs:element name="datum_izdavanja" type="xs:date"/>
                <xs:element ref="st:licni_podaci"/>
                <xs:element name="izdavac_sertifikata" type="xs:string"/>
                <xs:element ref="st:vakcinacije"/>
                <xs:element ref="st:testovi"/>
                <xs:element minOccurs="0" ref="st:prelezana"/>
            </xs:sequence>
            <xs:attribute name="zahtev_za_sertifikat" type="xs:string"/>
            <xs:attribute name="potvrda_o_vakcinisanju"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TTest">
        <xs:sequence>
            <xs:element name="naziv" type="xs:string"/>
            <xs:element name="vrsta_uzorka" type="xs:string"/>
            <xs:element name="proizvodjac" type="xs:string"/>
            <xs:element name="datum_vreme_uzorka" type="xs:dateTime"/>
            <xs:element name="datum_vreme_rezultata" type="xs:dateTime"/>
            <xs:element name="rezultat">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Pozitivan"/>
                        <xs:enumeration value="Negativan"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="laboratorija" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TLicni_podaci">
        <xs:sequence>
            <xs:element name="ime_prezime" type="fv:Ime_prezime"> </xs:element>
            <xs:element maxOccurs="1" minOccurs="1" name="pol" type="fv:pol"> </xs:element>
            <xs:element name="JMBG" type="fv:JMBG"> </xs:element>
            <xs:element name="broj_pasosa" type="fv:broj_pasosa"> </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TVakcinacija">
        <xs:sequence>
            <xs:element name="doza" type="xs:positiveInteger"/>
            <xs:element name="tip" type="xs:string"/>
            <xs:element name="proizvodjac" type="fv:tip_vakcine"/>
            <xs:element name="datum" type="xs:date"/>
            <xs:element name="zdravstvena_ustanova" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="licni_podaci" type="st:TLicni_podaci"> </xs:element>
    <xs:element name="vakcinacija" type="st:TVakcinacija"> </xs:element>
    <xs:element name="vakcinacije">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="st:vakcinacija" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="testovi">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="st:test" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="test" type="st:TTest"> </xs:element>
    <xs:element name="prelezana">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="datum_pozitivnog" type="xs:date"/>
                <xs:element name="laboratorija" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== blagojevic-uros/XML/Spring-JAX-RS/src/main/resources/podaci/xml/zeleni_sertifikat.xml
<?xml version="1.0" encoding="UTF-8"?>
<zeleni_sertifikat xmlns="http://ftn.uns.ac.rs/vakcina/sertifikat"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://ftn.uns.ac.rs/vakcina/sertifikat file:/D:/faks/4godina/xmlWebServiS/projekat/XML/Spring-JAX-RS/src/main/resources/podaci/schemas/zeleni_sertifikat.xsd"
                   xmlns:pred="http://www.ftn.uns.ac.rs/rdf/zahtev/predicate/"
                   about="http://www.ftn.uns.ac.rs/rdf/sertifikat/123123123/21"
                   rel="pred:potvrda" href="http://www.ftn.uns.ac.rs/rdf/potvrda/123"
>
    <QR_code></QR_code>
    <broj_sertifikata>1231231/21</broj_sertifikata>
    <datum_izdavanja property="pred:datum">2021-12-12</datum_izdavanja>
    <licni_podaci>
        <ime_prezime>
            <ime xmlns="http://ftn.uns.ac.rs/vakcina/tipovi">Aca</ime>
            <prezime xmlns="http://ftn.uns.ac.rs/vakcina/tipovi">Acovic</prezime>
        </ime_prezime>
        <pol>M</pol>
        <JMBG property="pred:jmbg">1231231231234</JMBG>
        <broj_pasosa>123123123</broj_pasosa>
    </licni_podaci>
    <izdavac_sertifikata property="pred:izdavac">Novi Sad Bolnica</izdavac_sertifikata>
    <vakcinacije>
        <vakcinacija>
            <doza>1</doza>
            <tip>123</tip>
            <proizvodjac property="pred:vakcina">AstraZeneca</proizvodjac>
            <datum>2021-12-12</datum>
            <zdravstvena_ustanova>Novi Sad Bolnica</zdravstvena_ustanova>
        </vakcinacija>
    </vakcinacije>
    <testovi>
        <test>
            <naziv property="pred:test">PCR test</naziv>
            <vrsta_uzorka></vrsta_uzorka>
            <proizvodjac></proizvodjac>
            <datum_vreme_uzorka>2021-12-12T12:12:00</datum_vreme_uzorka>
            <datum_vreme_rezultata>2021-12-13T12:12:00</datum_vreme_rezultata>
            <rezultat>Negativan</rezultat>
            <laboratorija></laboratorija>
        </test>
    </testovi>
</zeleni_sertifikat>

=== blagojevic-uros/XML/xml/zeleni_sertifikat.xml
<?xml version="1.0" encoding="UTF-8"?>
<zeleni_sertifikat xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/F:/4.%20Godina/XML/XML/schemas/zeleni_sertifikat.xsd">
    <QR_code></QR_code>
    <broj_sertifikata>1785483/21</broj_sertifikata>
    <datum_izdavanja>2021-11-04</datum_izdavanja>
    <licni_podaci>
        <ime_prezime>
            <ime>Aleksandar</ime>
            <prezime>Jovanović</prezime>
        </ime_prezime>
        <pol>Musko</pol>
        <JMBG>0808999742049</JMBG>
        <broj_pasosa>012001139</broj_pasosa>
    </licni_podaci>
    <izdavac_sertifikata>Institute of Public Health of Serbia "Dr Milan Jovanović Batut"</izdavac_sertifikata>
    <vakcinacije>
    
    </vakcinacije>
    <testovi>
       
    </testovi>
    <prelezana>
        <datum_pozitivnog>2021-08-02</datum_pozitivnog>
        <laboratorija>Opšta bolnica Vranje</laboratorija>
    </prelezana>
</zeleni_sertifikat>
