=== blagojevic-uros/XML/schemas/izvestaj.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.1">

    <xs:element name="izvestaj_o_imunizaciji">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pocetni_datum" type="xs:date"/>
                <xs:element name="zavrsni_datum">
                    <xs:simpleType>
                        <xs:restriction base="xs:date"/>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="broj_dokumenata_imunizaciju" type="xs:positiveInteger"/>
                <xs:element name="zahtevi_sertifikat" type="xs:positiveInteger"/>
                <xs:element name="izdati_zahtevi_sertifikat" type="xs:positiveInteger"/>
                <xs:element name="broj_doza" type="xs:positiveInteger"/>
                <xs:element ref="raspored_doza_vakcina_broj_doze"/>
                <xs:element ref="raspored_doza_vakcina_proizvodjac"/>
                <xs:element name="datum" type="xs:date"/>
                <xs:element name="potpis" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="raspored_doza_vakcina_proizvodjac">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Pfizer" type="xs:positiveInteger"/>
                <xs:element name="Sinopharm" type="xs:positiveInteger"/>
                <xs:element name="Sputnik_V" type="xs:positiveInteger"/>
                <xs:element name="AstraZeneca" type="xs:positiveInteger"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="raspored_doza_vakcina_broj_doze">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="doza_1" type="xs:positiveInteger"/>
                <xs:element name="doza_2" type="xs:positiveInteger"/>
                <xs:element name="doza_3" type="xs:positiveInteger"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== blagojevic-uros/XML/xml/izvestaj.xml
<?xml version="1.0" encoding="UTF-8"?>
<izvestaj_o_imunizaciji xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/F:/4.%20Godina/XML/XML/schemas/izvestaj.xsd">
    <pocetni_datum>2021-08-01</pocetni_datum>
    <zavrsni_datum>2021-09-01</zavrsni_datum>
    <broj_dokumenata_imunizaciju>2758</broj_dokumenata_imunizaciju>
    <zahtevi_sertifikat>453</zahtevi_sertifikat>
    <izdati_zahtevi_sertifikat>428</izdati_zahtevi_sertifikat>
    <broj_doza>3225</broj_doza>
    <raspored_doza_vakcina_broj_doze>
        <doza_1>1789</doza_1>
        <doza_2>1276</doza_2>
        <doza_3>160</doza_3>
    </raspored_doza_vakcina_broj_doze>
    <raspored_doza_vakcina_proizvodjac>
        <Pfizer>1625</Pfizer>
        <Sinopharm>1100</Sinopharm>
        <Sputnik_V>356</Sputnik_V>
        <AstraZeneca>144</AstraZeneca>
    </raspored_doza_vakcina_proizvodjac>
    <datum>2022-09-11</datum>
    <potpis>AJovanovic</potpis>
</izvestaj_o_imunizaciji>
